# Generated by Django 3.0.4 on 2020-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='chemin',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='pics/no-img.jpg', upload_to='pics'),
        ),
    ]
