# Generated by Django 3.0.4 on 2020-05-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('codePostale', models.IntegerField()),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DE', 'Defaut'), ('EX', 'Exceptionnel')], default='DE', max_length=2)),
                ('jour', models.CharField(choices=[('L', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('J', 'Jeudi'), ('V', 'Vendredi'), ('S', 'Samedi'), ('D', 'Dimanche')], max_length=2)),
                ('heureOuverture', models.TimeField(help_text='Utilisez le format "xx:xx" s\'il vous plait.')),
                ('heureFermeture', models.TimeField(help_text='Utilisez le format "xx:xx" s\'il vous plait.')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Adresse')),
            ],
        ),
    ]
