# Generated by Django 3.0.4 on 2020-05-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='categorie')),
                ('ordre_tri', models.IntegerField()),
            ]
        ),
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('nomCLient', models.CharField(max_length=50)),
                ('prenomClient', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('prixCommande', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProdAttr',
            fields=[
                ('idAttr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Attribut')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorie', models.ForeignKey(to='Categorie', on_delete=models.PROTECT)),
                ('special', models.BooleanField(default=False)),
                ('en_vente', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=150)),
                ('ordreTri', models.IntegerField()),
                ('image', models.ImageField(default='pics/no-img.jpg', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('idAttr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.ProdAttr')),
            ],
        ),
        migrations.AddField(
            model_name='prodattr',
            name='idProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Produit'),
        ),
        migrations.CreateModel(
            name='CommProd',
            fields=[
                ('quantite', models.IntegerField()),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prixLigne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Commandes')),
                ('idProduits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='commandes',
            name='idProduits',
            field=models.ManyToManyField(through='produits.CommProd', to='produits.Produit'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='idProd',
            field=models.ManyToManyField(through='produits.ProdAttr', to='produits.Produit'),
        ),
    ]
