# Generated by Django 3.0.4 on 2020-05-15 15:10

from django.db import migrations, models
from django.db.models.deletion import CASCADE, PROTECT


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField('categorie')),
                ('ordre_tri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(max_digits=5, decimal_places=2)),
                ('categorie', models.ForeignKey('Categorie', PROTECT)),
                ('special', models.BooleanField(default=False)),
                ('en_vente', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=150)),
                ('ordre_tri', models.IntegerField()),
                ('image', models.ImageField()),
            ],
        ),
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('attribut', models.ForeignKey('Attribut', CASCADE)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAttribut',
            fields=[
                ('produit', models.ForeignKey('Produit', CASCADE)),
                ('attribut', models.ForeignKey('Attribut', CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAttributValeur',
            fields=[
                ('produit_attribut', models.ForeignKey('ProduitAttribut', CASCADE)),
                ('valeur', models.ForeignKey('Valeur', CASCADE)),
                ('prix_extra', models.DecimalField(max_digits=5, decimal_places=2)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('nom_client', models.CharField(max_length=100)),
                ('prenomClient', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('prix_total', models.DecimalField(max_digits=5, decimal_places=2)),
                ('date_recuperation', models.DateField(null=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('est_validee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('commande', models.ForeignKey('Commande', CASCADE)),
                ('produit', models.ForeignKey('Produit', PROTECT)),
                ('produit_attribut_valeurs', models.ManyToManyField('ProduitAttributValeur')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(max_digits=5, decimal_places=2)),
                ('prix_total', models.DecimalField(max_digits=5, decimal_places=2)),
            ],
        ),
    ]
