# Generated by Django 3.0.4 on 2020-05-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCLient', models.CharField(max_length=50)),
                ('prenomClient', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('prixCommande', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProdAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAttr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Attribut')),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduits', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorie', models.CharField(choices=[('B', 'Boulangerie'), ('FB', 'Fine Boulangerie'), ('PAI', 'Pain'), ('PAT', 'Patisserie'), ('T', 'Tarte')], max_length=3)),
                ('special', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=150)),
                ('ordreTri', models.IntegerField()),
                ('image', models.ImageField(default='pics/no-img.jpg', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('idAttr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.ProdAttr')),
            ],
        ),
        migrations.AddField(
            model_name='prodattr',
            name='idProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Produits'),
        ),
        migrations.CreateModel(
            name='CommProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prixLigne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Commandes')),
                ('idProduits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Produits')),
            ],
        ),
        migrations.AddField(
            model_name='commandes',
            name='idProduits',
            field=models.ManyToManyField(through='produits.CommProd', to='produits.Produits'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='idProd',
            field=models.ManyToManyField(through='produits.ProdAttr', to='produits.Produits'),
        ),
    ]
